# Inserts a blank line between shell prompts
add_newline = false

# Replace the 'â¯' symbol in the prompt with 'âœ'
#[character] # The name of the module we are configuring is 'character'
#success_symbol = '[ó°°¸ âœ](bold green)' # The 'success_symbol' segment is being set to 'âœ' with the color 'bold green'
command_timeout = 200
#format = "[$directory$git_branch$git_status]($style)$character"
#format = "[$directory$git_branch$git_status]($style)$character"
#format = '$username $hostname $all'

[username]
show_always = true
style_user = "green bold"
format = "[$user]($style) "

#[hostname]
#disabled = false
# Optional: configure how the hostname is displayed
#ssh_only = false
#style = "green bold"
#format = "[$user]($style) "

[character]
error_symbol = "[âœ—](bold red)"
success_symbol = "[â¯](bold cyan)"

[directory]
truncation_length = 4
truncation_symbol = "â€¦/"
repo_root_style = "bold cyan"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[git_branch]
format = "[$branch]($style) "
style = "italic cyan"

[git_status]
format     = '[$all_status]($style)'
style      = "cyan"
ahead      = "â‡¡${count} "
diverged   = "â‡•â‡¡${ahead_count}â‡£${behind_count} "
behind     = "â‡£${count} "
conflicted = "î®« "
up_to_date = "ï€Œ "
untracked  = "? "
modified   = "î©± "
stashed    = ""
staged     = ""
renamed    = ""
deleted    = ""


[shell]
disabled = false
bash_indicator = "î¯Šîš‘"
xonsh_indicator = "ğŸ"
zsh_indicator = "[ó°°¸](bold green)"
powershell_indicator = "î¯‡"
fish_indicator = "ó°ˆºğŸŸ"
nu_indicator = "â˜¢ï¸"
elvish_indicator = 'ğŸ•ºğŸ¤ğŸ¸ğŸ‘‘ğŸ•¶ï¸âœ' # The 'success_symbol' segment is being set to 'âœ' with the color 'bold green'
cmd_indicator = "î¯„"
tcsh_indicator = "ïŠ"
